services:
  redis:
    container_name: redis
    image: redis:7.2.4

    volumes:
      - ./_data:/data
      - ./_data/redis.conf:/data/redis.conf

    command: redis-server /data/redis.conf

    networks:
      - ss-network

networks:
  ss-network:
    external: true
    driver: bridge
