services:
  ss-webscraper:
    container_name: ss-webscraper
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - ${SS_WEB_PORT}:${SS_WEB_PORT}
    # restart: always
    env_file:
      - .env
    networks:
      - ss-network
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.2.4
    volumes:
      - ./_data:/data
      - ./_data/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf
    networks:
      - ss-network

  celery:
    container_name: celery
    build:
      context: .
    command: ["celery", "-A", "worker", "worker", "--loglevel=info"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - ss-network
    depends_on:
      - redis

  celery-beat:
    container_name: celery-beat
    build:
      context: .
    command: ["celery", "-A", "worker", "beat", "--loglevel=info"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - ss-network
    depends_on:
      - redis

networks:
  ss-network:
    driver: bridge
    external: true
