services:
  ss-webscraper:
    container_name: ss-webscraper
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - ${SS_WEB_PORT}:${SS_WEB_PORT}
    env_file:
      - .env
    networks:
      - ss-network
    depends_on:
      - ss-webscraper-redis
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  ss-webscraper-redis:
    container_name: ss-webscraper-redis
    image: redis:7.4.0
    ports:
      - '6381:6379'
    networks:
      - ss-network
    volumes:
      - ss_webscraper_redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  ss-webscraper-celery:
    container_name: ss-webscraper-celery
    build: .
    command: celery -A src.workers.tasks worker --loglevel=INFO --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - ss-webscraper-redis
    env_file:
      - .env
    networks:
      - ss-network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G

volumes:
  ss_webscraper_redis_data:

networks:
  ss-network:
    driver: bridge
    external: true
