services:
  celery:
    container_name: celery
    image: ss-web-ss-web
    command: [
        "celery",
        "-A",
        "worker",
        "worker",
        "--loglevel=info",
        # "--logfile=logs/celery.log",
      ]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    # depends_on:
    # - web
    # - redis
    networks:
      - ss-network

networks:
  ss-network:
    external: true
    driver: bridge
