version: '3.3'

services:
  ws-service:
    # container_name: ws-service
    image: ws-service:v0.0.1
    command: [ "/app/./boot.sh" ]


    restart: always
    # volumes:
      # - ./_certs:/etc/certs:ro
    #Configuracion Autoscaling de Traefik
    # deploy:
        # replicas: 2
    env_file:
      - .env
        
networks:
  red:
    external: true