version: "3.3"

services:
  celery:
    container_name: celery
    image: ws-service:v0.0.1
    command: ["celery", "-A", "app.tasks", "worker", "--loglevel=info"]
    # depends_on:
    # - redis
    env_file:
      - .env

networks:
  red:
    external: true
    driver: bridge
