services:
  ss-web:
    container_name: ss-web
    build:
      context: ../../
    volumes:
      - ./src:/app/src
    ports:
      - ${SS_WEB_PORT}:${SS_WEB_PORT}
    restart: always
    env_file:
      - .env
    networks:
      - ss-network

networks:
  ss-network:
    driver: bridge
    external: true
