services:

  dashboard:
    build: ./src
    command: ["celery", "--broker=redis://redis:6379/0", "flower", "--port=5555"]
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    # depends_on:
      # - web
      # - redis
      # - worker

networks:
  red:
    external: true
    driver: bridge